global:
  scrape_interval: 15s

scrape_configs:
  - job_name: brado-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - brado-analytics.brado-staging.svc.cluster.local:8000
